name: Create Gantt Chart Issue

on:
  schedule:
    cron: '0 23 * * *'  # 日本時間8時（UTCで23時）

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a new issue with Gantt chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"title": "New Gantt Chart for Today", "body": "## Gantt Chart\n\n- Task 1: Pending\n- Task 2: Pending\n- Task 3: Pending\n\nThis issue will track the Gantt chart for today."}' \
            https://api.github.com/repos/${{ github.repository }}/issues
